name = "soonblog"
compatibility_date = "2024-10-01"

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "fed461dc-20ec-4aa9-a911-a4d88b3fa6e9"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "fed461dc-20ec-4aa9-a911-a4d88b3fa6e9"